CREATE TABLE IF NOT EXISTS profiles
(
    id BIGSERIAL PRIMARY KEY,
    surname VARCHAR(45) NOT NULL,
    name VARCHAR(45) NOT NULL,
    patronymic VARCHAR(45) NOT NULL,
    email VARCHAR(254) NOT NULL,
    login VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
);